import type { Metadata } from "next";
import PublicInfoPage from "@/components/PublicInfoPage";
export const metadata: Metadata = { title: "Safety Center", description: "Safety guidance for employers and freelancers using TaraWork." };
export default function SafetyPage() { return <PublicInfoPage eyebrow="Trust and safety" title="TaraWork Safety Center" introduction="Learn how to recognize suspicious activity, protect your account, and report unsafe jobs or users." sections={[
  { heading: "Never pay to apply", paragraphs: ["Legitimate employers do not require candidates to pay an application fee, recharge an account, purchase gift cards, transfer cryptocurrency, or deposit money to unlock work. Stop communicating and report any user who makes such a request."] },
  { heading: "Common warning signs", bullets: ["Guaranteed income for very little work or pressure to act immediately.", "Requests to move immediately to an unverified Telegram, WhatsApp, or personal account.", "Requests for passwords, one-time codes, card details, or unnecessary identity documents.", "Cheque-overpayment, equipment-purchase, task-recharge, crypto, gift-card, or money-forwarding arrangements.", "Jobs asking for fake reviews, deceptive engagement, illegal activity, or use of your bank account."] },
  { heading: "Safer hiring and work", bullets: ["Verify the person, company, domain, job scope, deliverables, rate, and payment schedule.", "Keep important agreements and evidence in writing.", "Use staged deliverables for new working relationships and do not share sensitive credentials unnecessarily.", "Understand that a profile badge or automated match is not a guarantee of conduct, skill, payment, or identity."] },
  { heading: "Report a concern", paragraphs: ["Use available report tools or email hello@tarawork.online with the profile or job link, screenshots, dates, and a concise description. TaraWork may preserve relevant records, restrict content, or suspend accounts while reviewing a credible report. For immediate financial loss or threats, also contact your payment provider and local authorities."] },
]} />; }
