import type { Metadata } from "next";
import PublicInfoPage from "@/components/PublicInfoPage";
export const metadata: Metadata = { title: "Privacy Policy", description: "How TaraWork collects, uses, protects, and manages personal information." };
export default function PrivacyPage() { return <PublicInfoPage eyebrow="Legal" title="Privacy Policy" introduction="This policy explains how TaraWork handles information when freelancers, employers, visitors, and administrators use the platform." sections={[
  { heading: "Information we collect", bullets: ["Account and contact details such as name, email address, role, and profile information.", "Freelancer portfolios, work history, skills, rates, and information users choose to publish.", "Employer company details, job listings, applications, invitations, messages, and support requests.", "Verification documents when a user voluntarily participates in an identity or account review.", "Technical information such as browser, device, security logs, approximate location, and usage analytics."] },
  { heading: "How information is used", bullets: ["Operate accounts, profiles, job listings, messaging, matching, and support.", "Prevent abuse, investigate reports, enforce platform rules, and protect users.", "Improve platform performance and communicate important account or service updates.", "Comply with applicable legal requests and retain records where reasonably necessary."] },
  { heading: "Sharing and public information", paragraphs: ["Public profiles and public job pages can be viewed and indexed by search engines. TaraWork does not sell personal information. Information may be shared with infrastructure, email, analytics, security, and payment service providers only as needed to provide the service, or when legally required."] },
  { heading: "Data choices and retention", paragraphs: ["Users may update profile information in their account and may request access, correction, export, or deletion by contacting TaraWork. Some security, dispute, transaction, or legal records may be retained for a reasonable period after account deletion."] },
  { heading: "Security and minors", paragraphs: ["TaraWork uses reasonable administrative and technical safeguards, but no online service can guarantee absolute security. The service is not intended for children who cannot legally consent to the processing of their information in their jurisdiction."] },
]} />; }
