"use client";

import { useMemo, useState } from "react";
import { Archive, FilePenLine, Inbox, Mail, RefreshCw, RotateCcw, Search, Send, Trash2 } from "lucide-react";

type Folder = "inbox" | "sent" | "drafts" | "trash";

export default function AdminEmailInbox({ messages, refresh, reply }: { messages: any[]; refresh: () => void; reply: (id: string, body: string) => Promise<void> }) {
  const [items, setItems] = useState(messages);
  const [folder, setFolder] = useState<Folder>("inbox");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [replyBody, setReplyBody] = useState("");
  const [replying, setReplying] = useState(false);
  const trashed = (m: any) => Boolean(m.metadata?.trashedAt);
  const inFolder = (m: any, f: Folder) => f === "trash" ? trashed(m) : !trashed(m) && (f === "drafts" ? m.status === "draft" : f === "sent" ? m.direction === "outbound" && m.status !== "draft" : m.direction !== "outbound" && m.status !== "draft");
  const visible = useMemo(() => items.filter((m) => inFolder(m, folder)).filter((m) => `${m.from_name || ""} ${m.from_email || ""} ${m.to_email || ""} ${m.subject || ""} ${m.text_body || ""}`.toLowerCase().includes(query.toLowerCase())), [items, folder, query]);
  const selected = visible.find((m) => m.id === selectedId);
  const mutate = async (id: string, action: "read" | "unread" | "trash" | "restore") => {
    const response = await fetch("/api/admin/email-messages", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action }) });
    const data = await response.json();
    if (!response.ok) return window.alert(data.error || "Unable to update email.");
    setItems((current) => current.map((m) => m.id === id ? { ...m, metadata: data.metadata } : m));
    if (action === "trash" || action === "restore") setSelectedId(null);
  };
  const remove = async (id: string) => {
    if (!window.confirm("Permanently delete this email? This cannot be undone.")) return;
    const response = await fetch(`/api/admin/email-messages?id=${encodeURIComponent(id)}`, { method: "DELETE" });
    const data = await response.json();
    if (!response.ok) return window.alert(data.error || "Unable to delete email.");
    setItems((current) => current.filter((m) => m.id !== id)); setSelectedId(null);
  };
  const folders = [{ id: "inbox", label: "Inbox", icon: Inbox }, { id: "sent", label: "Sent", icon: Send }, { id: "drafts", label: "Drafts", icon: FilePenLine }, { id: "trash", label: "Trash", icon: Trash2 }] as const;
  return <div className="grid min-h-[680px] grid-cols-1 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm lg:grid-cols-[220px_360px_minmax(0,1fr)]">
    <aside className="border-b border-slate-200 bg-slate-50/80 p-4 lg:border-b-0 lg:border-r"><div className="mb-5 flex items-center gap-3 px-3 py-2"><div className="rounded-xl bg-indigo-600 p-2 text-white"><Mail className="h-5 w-5" /></div><div><h3 className="font-black text-slate-900">TaraWork Mail</h3><p className="text-[11px] font-semibold text-slate-400">Admin mailbox</p></div></div><nav className="flex gap-2 overflow-x-auto lg:block lg:space-y-1">{folders.map((f) => <button key={f.id} onClick={() => { setFolder(f.id); setSelectedId(null); }} className={`flex min-w-fit items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold lg:w-full ${folder === f.id ? "bg-indigo-100 text-indigo-800" : "text-slate-600 hover:bg-slate-100"}`}><f.icon className="h-4 w-4" /><span className="flex-1 text-left">{f.label}</span><span className="text-xs">{items.filter((m) => inFolder(m, f.id)).length}</span></button>)}</nav></aside>
    <section className={`border-slate-200 lg:border-r ${selected ? "hidden lg:block" : "block"}`}><div className="flex gap-2 border-b border-slate-200 p-4"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={`Search ${folder}`} className="w-full rounded-xl bg-slate-100 py-2.5 pl-10 pr-4 text-sm outline-none focus:ring-2 focus:ring-indigo-200" /></div><button onClick={refresh} className="rounded-xl p-2.5 text-slate-500 hover:bg-slate-100"><RefreshCw className="h-4 w-4" /></button></div><div className="max-h-[615px] divide-y divide-slate-100 overflow-y-auto">{visible.length ? visible.map((m) => <button key={m.id} onClick={() => { setSelectedId(m.id); if (!m.metadata?.isRead) void mutate(m.id, "read"); }} className={`block w-full p-4 text-left hover:bg-slate-50 ${selectedId === m.id ? "bg-indigo-50" : ""}`}><div className="flex gap-2"><p className={`flex-1 truncate text-sm text-slate-900 ${m.metadata?.isRead ? "font-semibold" : "font-black"}`}>{folder === "sent" ? `To: ${m.to_email || "Unknown"}` : m.from_name || m.from_email || "TaraWork"}</p>{!m.metadata?.isRead && <span className="mt-1.5 h-2 w-2 rounded-full bg-indigo-600" />}</div><p className="mt-1 truncate text-sm font-bold text-slate-700">{m.subject || "(No subject)"}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-400">{m.text_body}</p><p className="mt-2 text-[10px] font-bold uppercase text-slate-400">{m.created_at ? new Date(m.created_at).toLocaleString() : ""}</p></button>) : <div className="p-12 text-center"><Archive className="mx-auto h-9 w-9 text-slate-300" /><p className="mt-3 text-sm font-semibold text-slate-400">No messages in {folder}.</p></div>}</div></section>
    <section className={`${selected ? "block" : "hidden lg:flex"} min-w-0 flex-col`}>{selected ? <div className="flex-1 p-5 md:p-7"><div className="mb-5 flex justify-between"><button onClick={() => setSelectedId(null)} className="font-bold text-indigo-600 lg:hidden">← Back</button><div className="ml-auto flex gap-2"><button title={selected.metadata?.isRead ? "Mark unread" : "Mark read"} onClick={() => void mutate(selected.id, selected.metadata?.isRead ? "unread" : "read")} className="rounded-lg border p-2 text-slate-500"><Mail className="h-4 w-4" /></button>{folder === "trash" ? <><button title="Restore" onClick={() => void mutate(selected.id, "restore")} className="rounded-lg border p-2 text-slate-500"><RotateCcw className="h-4 w-4" /></button><button title="Delete permanently" onClick={() => void remove(selected.id)} className="rounded-lg border border-red-100 p-2 text-red-600"><Trash2 className="h-4 w-4" /></button></> : <button title="Move to trash" onClick={() => void mutate(selected.id, "trash")} className="rounded-lg border p-2 text-slate-500"><Trash2 className="h-4 w-4" /></button>}</div></div><h2 className="text-2xl font-black text-slate-900">{selected.subject || "(No subject)"}</h2><div className="mt-5 border-b pb-5 text-sm"><p className="font-bold text-slate-800">{selected.from_name || selected.from_email || "Unknown sender"}</p><p className="text-xs text-slate-400">From: {selected.from_email || "unknown"} · To: {selected.to_email || "unknown"}</p></div><div className="mt-6 whitespace-pre-wrap text-sm font-medium leading-7 text-slate-700">{selected.text_body}</div>{selected.direction !== "outbound" && folder !== "trash" && <div className="mt-8"><textarea value={replyBody} onChange={(e) => setReplyBody(e.target.value)} rows={6} placeholder="Write a professional response..." className="w-full rounded-xl border p-4 text-sm outline-none focus:ring-2 focus:ring-indigo-200" /><button onClick={async () => { setReplying(true); await reply(selected.id, replyBody); setReplyBody(""); setReplying(false); }} disabled={replying || !replyBody.trim()} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Send className="h-4 w-4" />{replying ? "Sending..." : "Send reply"}</button></div>}</div> : <div className="m-auto text-center"><Mail className="mx-auto h-12 w-12 text-slate-200" /><p className="mt-4 font-bold text-slate-400">Select an email to read</p></div>}</section>
  </div>;
}
