"use client";

import { useEffect, useState } from "react";
import { Bot, Check, ChevronDown, Clock3, FileText, Lightbulb, Loader2, Play, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";

type Config = { enabled: boolean; mode: "ideas" | "review" | "auto_publish"; schedule: "weekly" | "biweekly" | "monthly"; articlesPerRun: number; minimumKeywordScore: number; preferredCategories: string[]; tone: string; targetWords: number; lastRunAt: string | null; nextRunAt: string | null };
type Payload = { config: Config; runs: any[]; opportunities: any[]; aiConfigured: boolean; model: string; provider: string; connectionIssue: string | null };
const categories = ["Employer Hiring Guides", "Remote Jobs for Filipinos", "Virtual Assistant Guides", "Freelancer Career Tips"];

export default function BlogAutomationPanel({ onCreated }: { onCreated: () => void }) {
  const [data, setData] = useState<Payload | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [running, setRunning] = useState(false); const [expanded, setExpanded] = useState(true); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const load = async () => { const response = await fetch("/api/admin/blog-automation", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to load Blog Autopilot."); setData(payload); return payload as Payload; };
  useEffect(() => { void load().catch((cause) => setError(cause.message)).finally(() => setLoading(false)); }, []);
  const update = <K extends keyof Config>(key: K, value: Config[K]) => setData((current) => current ? { ...current, config: { ...current.config, [key]: value } } : current);
  const save = async () => { if (!data) return; setSaving(true); setError(""); setNotice(""); try { const response = await fetch("/api/admin/blog-automation", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data.config) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to save automation."); setData({ ...data, config: payload.config }); setNotice("Blog Autopilot configuration saved."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save automation."); } finally { setSaving(false); } };
  const run = async () => { const previousRunId = data?.runs[0]?.id; setRunning(true); setError(""); setNotice(""); try { const response = await fetch("/api/admin/blog-automation", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); const responseText = await response.text(); let payload: any; try { payload = JSON.parse(responseText); } catch { throw new Error(`The request connection closed with HTTP ${response.status} while generation may still be running.`); } if (!response.ok) throw new Error(payload.error || "Blog automation failed."); await load(); if (payload.result.created) onCreated(); setNotice(payload.result.created ? `${payload.result.created} article ${data?.config.mode === "auto_publish" ? "published" : "drafted"} successfully.` : payload.result.topics?.length ? `${payload.result.topics.length} content ideas prepared.` : "No new uncovered topic met the quality threshold."); } catch (cause) { let recovered: Payload | null = null; for (let attempt = 0; attempt < 8; attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 5000)); try { const refreshed = await load(); const latest = refreshed.runs[0]; if (latest?.id !== previousRunId && latest?.status !== "running") { recovered = refreshed; break; } } catch {} } const latest = recovered?.runs[0]; if (latest?.status === "completed") { setError(""); setNotice(`${Number(latest.created_count || 0)} article ${recovered?.config.mode === "auto_publish" ? "published" : "drafted"} successfully.`); if (Number(latest.created_count || 0) > 0) onCreated(); } else { setError(latest?.error_message || (cause instanceof Error ? cause.message : "Blog automation failed.")); } } finally { setRunning(false); } };
  if (loading) return <div className="rounded-2xl border border-slate-200 bg-white p-8"><Loader2 className="mx-auto h-5 w-5 animate-spin text-teal-600" /></div>;
  if (!data) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm font-bold text-rose-700">{error || "Run the Blog Autopilot database migration, then reload."}</div>;
  const lastRun = data.runs[0];
  return <section className="overflow-hidden rounded-3xl border border-slate-800 bg-slate-950 text-white shadow-xl">
    <button onClick={() => setExpanded((value) => !value)} className="flex w-full items-center gap-4 p-5 text-left sm:p-6"><div className="rounded-2xl bg-teal-500 p-3 text-white shadow-lg shadow-teal-950"><Bot className="h-6 w-6" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-black">Blog Autopilot</h3><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase tracking-wider ${data.config.enabled ? "bg-emerald-400/15 text-emerald-300" : "bg-white/10 text-slate-400"}`}>{data.config.enabled ? "Scheduled" : "Paused"}</span><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase tracking-wider ${data.aiConfigured ? "bg-blue-400/15 text-blue-300" : "bg-amber-400/15 text-amber-300"}`}>{data.aiConfigured ? `${data.provider} · ${data.model} ready` : data.connectionIssue || "AI configuration required"}</span></div><p className="mt-1 text-xs font-medium text-slate-400">SEO-driven topic selection, original article drafts, scheduling, and editorial control.</p></div><ChevronDown className={`h-5 w-5 text-slate-500 transition ${expanded ? "rotate-180" : ""}`} /></button>
    {expanded && <div className="border-t border-white/10">{(notice || error) && <div className={`border-b px-5 py-3 text-xs font-bold ${error ? "border-rose-400/20 bg-rose-400/10 text-rose-300" : "border-emerald-400/20 bg-emerald-400/10 text-emerald-300"}`}>{error || notice}</div>}
      <div className="grid gap-px bg-white/10 sm:grid-cols-4">{[
        { label: "Last run", value: lastRun?.status || "Not run", icon: Clock3 }, { label: "SEO opportunities", value: String(data.opportunities.length), icon: TrendingUp }, { label: "Articles created", value: String(data.runs.reduce((sum, item) => sum + Number(item.created_count || 0), 0)), icon: FileText }, { label: "Workflow", value: data.config.mode.replace("_", " "), icon: ShieldCheck },
      ].map((item) => <div key={item.label} className="bg-slate-950 p-4"><div className="flex items-center justify-between"><p className="text-[9px] font-black uppercase tracking-wider text-slate-500">{item.label}</p><item.icon className="h-3.5 w-3.5 text-teal-400" /></div><p className="mt-2 truncate text-lg font-black capitalize">{item.value}</p></div>)}</div>
      <div className="grid gap-6 p-5 sm:p-6 xl:grid-cols-[minmax(0,1.15fr)_minmax(320px,.85fr)]"><div className="space-y-5"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-teal-300">Publishing workflow</p><div className="mt-3 grid gap-2 sm:grid-cols-3">{[
        { id: "ideas", title: "Ideas only", detail: "Select topics without writing", icon: Lightbulb }, { id: "review", title: "Review drafts", detail: "Generate drafts for approval", icon: FileText }, { id: "auto_publish", title: "Auto publish", detail: "Publish qualified articles", icon: Sparkles },
      ].map((mode) => <button key={mode.id} onClick={() => update("mode", mode.id as Config["mode"])} className={`rounded-2xl border p-4 text-left ${data.config.mode === mode.id ? "border-teal-400 bg-teal-400/10" : "border-white/10 bg-white/[.03]"}`}><mode.icon className={`h-4 w-4 ${data.config.mode === mode.id ? "text-teal-300" : "text-slate-500"}`} /><p className="mt-3 text-sm font-black">{mode.title}</p><p className="mt-1 text-[10px] text-slate-500">{mode.detail}</p></button>)}</div></div>
      <div className="grid gap-3 rounded-2xl border border-white/10 bg-white/[.03] p-4 sm:grid-cols-2"><label className="text-[9px] font-black uppercase tracking-wider text-slate-500">Schedule<select value={data.config.schedule} onChange={(event) => update("schedule", event.target.value as Config["schedule"])} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-xs font-bold"><option value="weekly">Weekly</option><option value="biweekly">Every 2 weeks</option><option value="monthly">Monthly</option></select></label><label className="text-[9px] font-black uppercase tracking-wider text-slate-500">Articles per run<input type="number" min="1" max="3" value={data.config.articlesPerRun} onChange={(event) => update("articlesPerRun", Math.max(1, Math.min(3, Number(event.target.value))))} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-xs font-bold" /></label><label className="text-[9px] font-black uppercase tracking-wider text-slate-500">Target words<input type="number" min="700" max="2500" step="100" value={data.config.targetWords} onChange={(event) => update("targetWords", Number(event.target.value))} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-xs font-bold" /></label><label className="text-[9px] font-black uppercase tracking-wider text-slate-500">Minimum SEO score · {data.config.minimumKeywordScore}<input type="range" min="40" max="95" step="5" value={data.config.minimumKeywordScore} onChange={(event) => update("minimumKeywordScore", Number(event.target.value))} className="mt-3 w-full accent-teal-500" /></label></div>
      <label className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[.03] p-4"><span><span className="block text-sm font-black">Scheduled generation</span><span className="mt-1 block text-[10px] text-slate-500">The daily scheduler runs only when your selected cadence is due.</span></span><button type="button" onClick={() => update("enabled", !data.config.enabled)} className={`relative h-7 w-12 rounded-full ${data.config.enabled ? "bg-emerald-500" : "bg-slate-700"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${data.config.enabled ? "left-6" : "left-1"}`} /></button></label>
      <div className="flex flex-wrap gap-2"><button onClick={() => void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-black text-slate-950 disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />} Save automation</button><button onClick={() => void run()} disabled={running || (!data.aiConfigured && data.config.mode !== "ideas")} className="inline-flex items-center gap-2 rounded-xl bg-teal-500 px-4 py-2.5 text-xs font-black text-white disabled:opacity-40">{running ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}{running ? "Creating content…" : "Run now"}</button></div></div>
      <aside className="space-y-4"><div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><h4 className="text-sm font-black">Preferred categories</h4><div className="mt-3 space-y-2">{categories.map((category) => { const checked = data.config.preferredCategories.includes(category); return <label key={category} className="flex items-center gap-3 rounded-xl bg-black/15 px-3 py-2.5"><input type="checkbox" checked={checked} onChange={() => update("preferredCategories", checked ? data.config.preferredCategories.filter((item) => item !== category) : [...data.config.preferredCategories, category])} className="h-4 w-4 rounded accent-teal-500" /><span className="text-xs font-bold text-slate-300">{category}</span></label>; })}</div></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><h4 className="text-sm font-black">Next topic opportunities</h4><div className="mt-3 space-y-2">{data.opportunities.slice(0, 5).map((item) => <div key={item.keyword} className="flex items-center justify-between gap-3 rounded-xl bg-black/15 px-3 py-2.5"><div className="min-w-0"><p className="truncate text-xs font-black capitalize">{item.keyword}</p><p className="mt-1 text-[9px] uppercase text-slate-500">{item.intent}</p></div><span className="rounded-lg bg-teal-400/10 px-2 py-1 text-[10px] font-black text-teal-300">{item.opportunity_score}</span></div>)}</div></div></aside></div>
    </div>}
  </section>;
}
