"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Activity, Bot, Check, ChevronDown, ExternalLink, Gauge, History, Loader2, Play, RefreshCw, RotateCcw, Search, ShieldCheck, Sparkles, TrendingUp, X } from "lucide-react";

type Config = { enabled: boolean; mode: "monitor" | "approval" | "safe_autopilot"; schedule: "daily" | "weekly" | "monthly"; seedKeywords: string[]; minimumScore: number; maxChangesPerRun: number; protectHomeMetadata: boolean; googleSiteUrl: string; lastRunAt: string | null; nextRunAt: string | null };
type Payload = { config: Config; integration: { connected: boolean; configured: boolean; account?: { account_email?: string; account_name?: string } }; runs: any[]; changes: any[]; opportunities: any[] };

export default function SeoAutopilotPanel() {
  const [data, setData] = useState<Payload | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [running, setRunning] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [seedDraft, setSeedDraft] = useState(""); const [expanded, setExpanded] = useState(true);
  const load = async () => { const response = await fetch("/api/admin/seo-automation", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to load SEO Autopilot."); setData(payload); };
  useEffect(() => { void load().catch((cause) => setError(cause.message)).finally(() => setLoading(false)); }, []);
  const setConfig = <K extends keyof Config>(key: K, value: Config[K]) => setData((current) => current ? { ...current, config: { ...current.config, [key]: value } } : current);
  const save = async () => { if (!data) return; setSaving(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/seo-automation", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data.config) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to save automation."); setData({ ...data, config: payload.config }); setMessage("SEO Autopilot configuration saved."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save automation."); } finally { setSaving(false); } };
  const run = async () => { setRunning(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/seo-automation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "run" }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Automation run failed."); await load(); setMessage(`Analysis complete: ${payload.result.discovered} discovered, ${payload.result.qualified || 0} qualified, ${payload.result.applied || 0} automatically applied.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Automation run failed."); } finally { setRunning(false); } };
  const changeAction = async (action: "approve" | "reject" | "rollback", changeId: string) => { if (action === "rollback" && !confirm("Restore the SEO settings from before this change?")) return; setSaving(true); try { const response = await fetch("/api/admin/seo-automation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, changeId }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to process change."); await load(); setMessage(action === "approve" ? "SEO proposal approved and published." : action === "rollback" ? "SEO change rolled back." : "SEO proposal rejected."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to process change."); } finally { setSaving(false); } };

  if (loading) return <div className="rounded-2xl border border-slate-200 p-8"><Loader2 className="mx-auto h-5 w-5 animate-spin text-indigo-600" /></div>;
  if (!data) return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5"><p className="font-black text-rose-800">SEO Autopilot database setup required</p><p className="mt-2 text-xs leading-5 text-rose-700">{error || "Run the SEO Autopilot section in supabase_schema.sql, then reload this page."}</p></div>;
  const lastRun = data.runs[0]; const topOpportunity = data.opportunities[0];
  return <section className="overflow-hidden rounded-3xl border border-slate-800 bg-slate-950 text-white shadow-2xl shadow-slate-200">
    <button type="button" onClick={() => setExpanded((value) => !value)} className="flex w-full items-center gap-4 p-5 text-left sm:p-6"><div className="rounded-2xl bg-indigo-500 p-3 shadow-lg shadow-indigo-950"><Bot className="h-6 w-6" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-black">SEO Autopilot</h3><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase tracking-wider ${data.config.enabled ? "bg-emerald-400/15 text-emerald-300" : "bg-white/10 text-slate-400"}`}>{data.config.enabled ? "Automation active" : "Automation paused"}</span></div><p className="mt-1 text-xs font-medium text-slate-400">Closed-loop discovery, approval, publishing, performance signals, and rollback.</p></div><ChevronDown className={`h-5 w-5 text-slate-500 transition ${expanded ? "rotate-180" : ""}`} /></button>
    {expanded && <div className="border-t border-white/10">
      {(message || error) && <div className={`border-b px-5 py-3 text-xs font-bold ${error ? "border-rose-400/20 bg-rose-400/10 text-rose-300" : "border-emerald-400/20 bg-emerald-400/10 text-emerald-300"}`}>{error || message}</div>}
      <div className="grid gap-px bg-white/10 sm:grid-cols-2 xl:grid-cols-4">{[
        { label: "Last run", value: lastRun?.status || "Not run", detail: lastRun?.started_at ? new Date(lastRun.started_at).toLocaleString() : "Ready for first analysis", icon: Activity },
        { label: "Opportunities", value: String(data.opportunities.length), detail: topOpportunity ? `Top score: ${topOpportunity.opportunity_score}` : "Run discovery to populate", icon: TrendingUp },
        { label: "Changes", value: String(data.changes.length), detail: `${data.changes.filter((item) => item.status === "proposed").length} awaiting approval`, icon: History },
        { label: "Search Console", value: data.integration.connected ? "Connected" : "Not connected", detail: data.integration.account?.account_email || "Connect actual Google metrics", icon: Search },
      ].map((item) => <div key={item.label} className="bg-slate-950 p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-slate-500">{item.label}</p><item.icon className="h-4 w-4 text-indigo-400" /></div><p className="mt-2 text-xl font-black capitalize">{item.value}</p><p className="mt-1 truncate text-[10px] text-slate-500">{item.detail}</p></div>)}</div>
      <div className="grid gap-6 p-5 sm:p-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(360px,.9fr)]">
        <div className="space-y-5">
          <div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-indigo-300">Operating mode</p><div className="mt-3 grid gap-2 md:grid-cols-3">{[
            { id: "monitor", title: "Monitor", detail: "Discover and report only", icon: Gauge }, { id: "approval", title: "Approval", detail: "Prepare changes for review", icon: ShieldCheck }, { id: "safe_autopilot", title: "Safe autopilot", detail: "Apply low-risk targets", icon: Sparkles },
          ].map((mode) => <button type="button" key={mode.id} onClick={() => setConfig("mode", mode.id as Config["mode"])} className={`rounded-2xl border p-4 text-left transition ${data.config.mode === mode.id ? "border-indigo-400 bg-indigo-500/15" : "border-white/10 bg-white/[.03] hover:bg-white/[.06]"}`}><mode.icon className={`h-4 w-4 ${data.config.mode === mode.id ? "text-indigo-300" : "text-slate-500"}`} /><p className="mt-3 text-sm font-black">{mode.title}</p><p className="mt-1 text-[10px] leading-4 text-slate-500">{mode.detail}</p></button>)}</div></div>
          <div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-black">Scheduled automation</p><p className="mt-1 text-[10px] text-slate-500">The scheduler checks daily and runs only when the selected cadence is due.</p></div><button type="button" onClick={() => setConfig("enabled", !data.config.enabled)} className={`relative h-7 w-12 rounded-full transition ${data.config.enabled ? "bg-emerald-500" : "bg-slate-700"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${data.config.enabled ? "left-6" : "left-1"}`} /></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-black uppercase tracking-wider text-slate-500">Cadence<select value={data.config.schedule} onChange={(event) => setConfig("schedule", event.target.value as Config["schedule"])} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-xs font-bold text-white"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label className="text-[10px] font-black uppercase tracking-wider text-slate-500">Minimum score · {data.config.minimumScore}<input type="range" min="50" max="95" step="5" value={data.config.minimumScore} onChange={(event) => setConfig("minimumScore", Number(event.target.value))} className="mt-3 w-full accent-indigo-500" /></label><label className="text-[10px] font-black uppercase tracking-wider text-slate-500">Maximum changes<input type="number" min="1" max="10" value={data.config.maxChangesPerRun} onChange={(event) => setConfig("maxChangesPerRun", Math.max(1, Math.min(10, Number(event.target.value))))} className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-xs font-bold text-white" /></label><label className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5"><span><span className="block text-[10px] font-black uppercase tracking-wider text-slate-500">Protect homepage</span><span className="mt-1 block text-[9px] text-slate-600">Keywords only; never rewrite title</span></span><input type="checkbox" checked={data.config.protectHomeMetadata} onChange={(event) => setConfig("protectHomeMetadata", event.target.checked)} className="h-4 w-4 rounded accent-indigo-500" /></label></div></div>
          <div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><p className="text-sm font-black">Discovery topics</p><div className="mt-3 flex gap-2"><input value={seedDraft} onChange={(event) => setSeedDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && seedDraft.trim()) { event.preventDefault(); setConfig("seedKeywords", [...data.config.seedKeywords, seedDraft.trim()].slice(0, 12)); setSeedDraft(""); } }} placeholder="Add market, service, or audience" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-xs font-bold outline-none focus:border-indigo-400" /><button type="button" onClick={() => { if (seedDraft.trim()) { setConfig("seedKeywords", [...data.config.seedKeywords, seedDraft.trim()].slice(0, 12)); setSeedDraft(""); } }} className="rounded-xl bg-white px-3 text-xs font-black text-slate-950">Add</button></div><div className="mt-3 flex flex-wrap gap-2">{data.config.seedKeywords.map((seed) => <span key={seed} className="inline-flex items-center gap-1.5 rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-bold text-slate-300">{seed}<button onClick={() => setConfig("seedKeywords", data.config.seedKeywords.filter((item) => item !== seed))}><X className="h-3 w-3" /></button></span>)}</div></div>
          <div className="flex flex-wrap gap-2"><button onClick={() => void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-black text-slate-950 disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />} Save automation</button><button onClick={() => void run()} disabled={running} className="inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-4 py-2.5 text-xs font-black text-white disabled:opacity-50">{running ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />} {running ? "Analyzing the web…" : "Run now"}</button></div>
        </div>
        <div className="space-y-5">
          <div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-black">Google Search Console</p><p className="mt-1 text-[10px] text-slate-500">Actual queries, clicks, impressions, CTR, and position.</p></div>{data.integration.connected && <span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[9px] font-black text-emerald-300">Connected</span>}</div>{data.integration.connected ? <><label className="mt-4 block text-[10px] font-black uppercase tracking-wider text-slate-500">Property URL<input value={data.config.googleSiteUrl} onChange={(event) => setConfig("googleSiteUrl", event.target.value)} placeholder="https://www.tarawork.online/ or sc-domain:tarawork.online" className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2.5 text-xs font-bold" /></label><p className="mt-2 text-[10px] text-slate-500">Connected as {data.integration.account?.account_email || "Google account"}</p></> : <Link href="/api/admin/seo-automation/google/connect" prefetch={false} className="mt-4 inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white px-4 py-2.5 text-xs font-black text-slate-950">Connect Google <ExternalLink className="h-3.5 w-3.5" /></Link>}</div>
          <div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="flex items-center justify-between"><p className="text-sm font-black">Top opportunities</p><button onClick={() => void load()} className="text-slate-500 hover:text-white"><RefreshCw className="h-4 w-4" /></button></div><div className="mt-3 space-y-2">{data.opportunities.slice(0, 6).map((item) => <div key={item.id} className="rounded-xl border border-white/5 bg-black/15 p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-black capitalize">{item.keyword}</p><p className="mt-1 text-[9px] uppercase tracking-wider text-slate-500">{item.intent} · {item.impressions ? `${item.impressions} impressions` : item.source?.join(" + ")}</p></div><span className={`rounded-lg px-2 py-1 text-[10px] font-black ${item.opportunity_score >= 80 ? "bg-emerald-400/10 text-emerald-300" : "bg-indigo-400/10 text-indigo-300"}`}>{item.opportunity_score}</span></div></div>)}{!data.opportunities.length && <p className="py-6 text-center text-[10px] text-slate-500">Run the first analysis to populate opportunities.</p>}</div></div>
        </div>
      </div>
      {data.changes.length > 0 && <div className="border-t border-white/10 p-5 sm:p-6"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-slate-500">Change control & rollback</p><div className="mt-3 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[760px] text-left"><thead className="bg-white/[.04] text-[9px] font-black uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Change</th><th className="px-4 py-3">Confidence</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Date</th><th className="px-4 py-3 text-right">Control</th></tr></thead><tbody className="divide-y divide-white/5">{data.changes.slice(0, 8).map((change) => <tr key={change.id}><td className="px-4 py-3"><p className="text-xs font-black">{change.reason}</p><p className="mt-1 text-[9px] text-slate-500">{change.target_page}</p></td><td className="px-4 py-3 text-xs font-black">{change.confidence}%</td><td className="px-4 py-3"><span className="rounded-full bg-white/10 px-2 py-1 text-[9px] font-black uppercase text-slate-300">{change.status.replace("_", " ")}</span></td><td className="px-4 py-3 text-[10px] text-slate-500">{new Date(change.applied_at).toLocaleString()}</td><td className="px-4 py-3"><div className="flex justify-end gap-2">{change.status === "proposed" && <><button onClick={() => void changeAction("reject", change.id)} className="rounded-lg border border-white/10 px-2.5 py-1.5 text-[9px] font-black text-slate-400">Reject</button><button onClick={() => void changeAction("approve", change.id)} className="rounded-lg bg-emerald-500 px-2.5 py-1.5 text-[9px] font-black text-white">Approve</button></>}{change.status === "applied" && <button onClick={() => void changeAction("rollback", change.id)} className="inline-flex items-center gap-1.5 rounded-lg border border-amber-400/20 px-2.5 py-1.5 text-[9px] font-black text-amber-300"><RotateCcw className="h-3 w-3" /> Rollback</button>}</div></td></tr>)}</tbody></table></div></div>}
    </div>}
  </section>;
}
