import type { Metadata } from "next";
import PublicInfoPage from "@/components/PublicInfoPage";
export const metadata: Metadata = { title: "Terms of Service", description: "Terms governing use of the TaraWork freelance marketplace." };
export default function TermsPage() { return <PublicInfoPage eyebrow="Legal" title="Terms of Service" introduction="These terms govern access to TaraWork. By creating an account or using the platform, you agree to use it lawfully and provide accurate information." sections={[
  { heading: "Platform role", paragraphs: ["TaraWork provides tools for talent discovery, profiles, job listings, applications, invitations, communication, and related marketplace functions. Unless explicitly stated for a specific transaction, TaraWork is not the employer, employee, client, freelancer, recruiter, bank, insurer, or legal representative of users."] },
  { heading: "User responsibilities", bullets: ["Provide accurate account, identity, company, portfolio, job, and payment information.", "Do not impersonate others, misrepresent qualifications, publish deceptive jobs, or manipulate reviews.", "Do not request application fees, advance-task payments, gift cards, cryptocurrency transfers, or other suspicious payments.", "Comply with employment, tax, privacy, intellectual-property, and consumer laws that apply to you.", "Protect account credentials and report unauthorized access promptly."] },
  { heading: "Jobs, contracts, and payments", paragraphs: ["Users are responsible for evaluating each other, agreeing on scope, deliverables, compensation, tax treatment, and legal terms. Features described as verification, matching, payment, or dispute tools are limited to the functionality expressly shown in the platform and are not a guarantee of identity, performance, payment, or outcome."] },
  { heading: "Moderation and termination", paragraphs: ["TaraWork may review, restrict, remove, or suspend accounts or content that violate these terms, create safety risks, infringe rights, or expose the platform or users to abuse. Users may contact support to request a review of a moderation decision."] },
  { heading: "Disclaimers and liability", paragraphs: ["The service is provided on an as-available basis. TaraWork does not guarantee continuous availability, job placement, candidate quality, income, hiring outcomes, or the conduct of another user. Liability is limited to the extent permitted by applicable law."] },
]} />; }
