import { Job } from "../types";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "React Developer for E-commerce",
    description: "Senior react developer needed for a 3-month project.",
    company: "TechPH",
    category: "Developer",
    paymentMethod: "Hourly",
    rate: "$25/hr",
    duration: "1-3 months",
    skills: ["React", "TypeScript", "Tailwind"],
    createdAt: "2024-02-23",
  },
  {
    id: "2",
    title: "Next.js Fullstack Developer",
    description: "Building a dashboard using Next.js and Serverless functions.",
    company: "Startup Hub",
    category: "Developer",
    paymentMethod: "Flat-Rate",
    rate: "$1500",
    duration: "Ongoing",
    skills: ["Next.js", "Node.js", "PostgreSQL"],
    createdAt: "2024-02-22",
  },
  {
    id: "3",
    title: "UI/UX Designer",
    description: "Design for a mobile app.",
    company: "Creative Co.",
    category: "Designer",
    paymentMethod: "Hourly",
    rate: "$30/hr",
    duration: "1-2 weeks",
    skills: ["Figma", "UI/UX"],
    createdAt: "2024-02-21",
  },
  {
    id: "4",
    title: "Virtual Executive Assistant",
    description: "Looking for a highly organized VA to manage schedules and emails.",
    company: "Global Ops",
    category: "Virtual Assistant",
    paymentMethod: "Hourly",
    rate: "$15/hr",
    duration: "Ongoing",
    skills: ["Calendar Management", "Email Outreach", "English"],
    createdAt: "2024-02-24",
  },
  {
    id: "5",
    title: "Technical Content Writer",
    description: "Write blog posts about cloud computing and devops.",
    company: "Cloud Pro",
    category: "Writer",
    paymentMethod: "Flat-Rate",
    rate: "$200/article",
    duration: "1-2 weeks",
    skills: ["Technical Writing", "SEO", "Cloud"],
    createdAt: "2024-02-24",
  },
  {
    id: "6",
    title: "Social Media Manager",
    description: "Manage Instagram and TikTok for a lifestyle brand.",
    company: "Vibe Media",
    category: "Marketing Specialist",
    paymentMethod: "Hourly",
    rate: "$20/hr",
    duration: "1-3 months",
    skills: ["Instagram", "TikTok", "Canva"],
    createdAt: "2024-02-24",
  },
];
