import { Job } from "../types";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "React Developer para sa E-commerce",
    description: "Kailangan ng senior react developer para sa 3-month project.",
    company: "TechPH",
    paymentMethod: "Hourly",
    rate: "$25/hr",
    duration: "1-3 months",
    skills: ["React", "TypeScript", "Tailwind"],
    createdAt: "2024-02-23",
  },
  {
    id: "2",
    title: "Next.js Fullstack Developer",
    description: "Pagbuo ng dashboard gamit ang Next.js at Serverless functions.",
    company: "Startup Hub",
    paymentMethod: "Flat-Rate",
    rate: "$1500",
    duration: "Ongoing",
    skills: ["Next.js", "Node.js", "PostgreSQL"],
    createdAt: "2024-02-22",
  },
  {
    id: "3",
    title: "UI/UX Designer",
    description: "Design para sa mobile app.",
    company: "Creative Co.",
    paymentMethod: "Hourly",
    rate: "$30/hr",
    duration: "1-2 weeks",
    skills: ["Figma", "UI/UX"],
    createdAt: "2024-02-21",
  },
  {
    id: "4",
    title: "Backend Engineer (Go)",
    description: "Kailangan ng Go expert para sa scaling.",
    company: "Fintech App",
    paymentMethod: "Flat-Rate",
    rate: "$5000",
    duration: "Ongoing",
    skills: ["Go", "Docker", "Kubernetes"],
    createdAt: "2024-02-20",
  },
  {
    id: "5",
    title: "Frontend Developer (Vue)",
    description: "Migration ng legacy app papuntang Vue 3.",
    company: "Legacy Systems",
    paymentMethod: "Hourly",
    rate: "$20/hr",
    duration: "1-2 weeks",
    skills: ["Vue", "JavaScript"],
    createdAt: "2024-02-19",
  },
];
