import type { Metadata } from "next";
import PublicInfoPage from "@/components/PublicInfoPage";
export const metadata: Metadata = { title: "Payment and Refund Policy", description: "Payment, fee, cancellation, dispute, and refund disclosures for TaraWork." };
export default function PaymentPolicyPage() { return <PublicInfoPage eyebrow="Payments" title="Payment and Refund Policy" introduction="This page explains TaraWork payment disclosures. Users should review the terms shown for a specific paid feature before completing a transaction." sections={[
  { heading: "No fee to apply", paragraphs: ["Freelancers should never pay an employer or recruiter merely to apply for a TaraWork job. Requests for application fees, task recharges, security deposits, gift cards, or cryptocurrency should be reported."] },
  { heading: "Platform and project payments", paragraphs: ["Any TaraWork platform fee will be disclosed before purchase. Payments agreed directly between an employer and freelancer are governed by their own contract and selected payment provider unless the platform explicitly states that a particular transaction is processed through a named TaraWork payment feature."] },
  { heading: "Refund requests", paragraphs: ["For a charge made directly by TaraWork, contact hello@tarawork.online with the account email, transaction reference, date, amount, and reason. Eligibility depends on the purchased feature, whether it has been delivered or used, applicable provider rules, and consumer law. Payments made directly to another user are not automatically refundable by TaraWork."] },
  { heading: "Disputes and chargebacks", paragraphs: ["Users should first document the agreed scope, delivery evidence, messages, and payment record. TaraWork may review platform records and moderate accounts but cannot guarantee recovery of funds held by an external provider or another user. Unauthorized charges should be reported promptly to TaraWork and the payment provider."] },
]} />; }
